### ISSUE TITLE
res101 test error

### ISSUE THREAD

**Issue by jwnsu** [endernewton/tf-faster-rcnn#15]
After setup, got following error (0712 version of model files):
"Loading model check point from output/res101/voc_2007_trainval/default/res101_faster_rcnn_iter_70000.ckpt
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [401408,84] rhs shape= [100352,84]"

Has no issue with vgg16 previously (tf 0.12). Env: ubuntu 16.04, cuda 8.0/cudnn 5.1 and Nvidia 1070.

**Comment by endernewton** [comment]
Oops, this is because I was updating the RoI pooling to use 14 x 14
directly instead of using 7 x 7 (which was how it is trained before). You
can change the crop_pool_layer in res101.py with the one used in vgg16.py.
Essentially adding slim.max_pool2d(crops, [2, 2], padding='SAME').

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by endernewton** [comment]
I have updated the instructions, closing the issue now. :)

**Comment by jwnsu** [comment]
ok, confirmed it is now working after change _crop_pool_layer as you suggested here.

**Comment by niuniu111** [comment]
Where can I get down to this model, 'res101_faster_rcnn_iter_110000.ckpt' ?
Seek help

**Comment by Adibhatt95** [comment]
was anyone able to get the model res101_faster_rcnn_iter_110000.ckpt' ?
