### ISSUE TITLE
OSError: output/res101/voc_2007_trainval/default/res101_faster_rcnn_iter_10000.ckpt.meta not found. Did you download the proper networks from our server and place them properly?

### ISSUE THREAD

**Issue by stevenshuang** [endernewton/tf-faster-rcnn#309]
The first time use it, i get this error, i dont't know how to solve it. According to the error, i find the file  res101_faster_rcnn_iter_10000.ckpt.meta, plealse help me, thanks

**Comment by pranavteddu** [comment]
You have to place the downloaded data in the data folder and unzip it.
It may be also because you may have named the folders wrong. In the step 
mkdir -p output/${NET}/${TRAIN_IMDB} you have to name the folders as res101 and voc_2007_trainval+voc_2012_trainval or the data set you have used.
  
use this : mkdir -p output/res101/voc_2007_trainval+voc_2012_trainval
and : cd output/res101/voc_2007_trainval+voc_2012_trainval
This has to solve your problem.

**Comment by stevenshuang** [comment]
Thanks!  I downloaded the data

**Comment by 1451595897** [comment]
I also have this problem today when I use the google colab to run the demo.py,how do you deal with it? @stevenshuang

**Comment by Emma-uestc** [comment]
Did you figure out this problem? I had encountered the same problem.
Evn: ubuntu os on aws
