### ISSUE TITLE
What does "depre" really mean?

### ISSUE THREAD

**Issue by EasonSun** [endernewton/tf-faster-rcnn#68]
Hi, 

Thank you for this effort. Why in the codes "depre" shows up from time to time? What gets deprecated and why you deprecate? What does this mean if I would like to do fine tune?

Thank you!

**Comment by zacwellmer** [comment]
depreciated. I believe it's because if you take pascal_voc pretrained model it will only be compatible w/ the depreciated version of scripts

**Comment by EasonSun** [comment]
Yes Zac I am fine tuning based on the pretrained models. Does this depre has other meanings?  Especially I am not sure if this depre can cause trouble with fine tuning. Why this word gets picked up instead of others, cause it usually means something bad?

**Comment by endernewton** [comment]
i mean depreciated. because when the code is first released, i am using the caffe weights, but then to accommodate more advanced nets, @philokey submitted a PR. this is wonderful since it opens up chances to train with all models that tensorflow can provide, but it can also include new bugs. so i am right now keeping those old models as deprecated ones (for other people to verify). once i verify that the new code can produce similar results, i will remove the old code and replace the old models, hopefully soon.

**Comment by endernewton** [comment]
the latest updates have removed the "depre" code. you are welcome to test it out and report bugs. :)
