### ISSUE TITLE
How to perform faster-rcnn on new dataset?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#95]
I have followed the instructions and managed to run the demo successfully. According to instructions, to train a model on another dataset, one should use a command like this:
`./experiments/scripts/train_faster_rcnn.sh [GPU_ID] [DATASET] [NET]`

where **[DATASET]** can be **pascal** or **coco**. How can I run it on another dataset where annotation files are in **.txt** format, whereas in pascal the annotations are in **xml**?

**Comment by kalaspuffar** [comment]
I've just done what you ask for. There is a few places you need to change the python code in order to accomplish that.

First of you need to copy the **pascal_voc.py** in **lib/datasets** directory and implement your own **_load_pascal_annotation** function.

Changing the classes your interested in and also where your data files are located could be done in the same file.

Next up you update the **factory.py** file to include your new dataset.

Lastly you need to update the 
**./experiments/scripts/train_faster_rcnn.sh** and **./experiments/scripts/test_faster_rcnn.sh** to include your dataset.

**Comment by SamyMe** [comment]
I think you can follow [this guide ](https://github.com/zeyuanxy/fast-rcnn/blob/master/help/train/README.md).

**Comment by hadi-ghnd** [comment]
Thank you for the helpful guidance. Where can I set the configurations like **number of iterations** or **Momentum** or **Batch Size** ,...?

**Comment by SamyMe** [comment]
You can change different params in  [lib/model/config.py](https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/model/config.py).

**Comment by hadi-ghnd** [comment]
Actually I have run the **pascal VOC** data based on [this page](https://github.com/smallcorgi/Faster-RCNN_TF). Do you happen to know a similar file like **config.py** in that page? thanks a lot for the help

**Comment by hadi-ghnd** [comment]
@SamyMe Is [ Faster-RCNN_TF/tools/train_net.py
](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/train_net.py) the file I should modify?

**Comment by lyltencent** [comment]
@kalaspuffar , Daniel, Could you please share some of your code on how to make the code working for a new custom dataset. Thank you.

**Comment by kalaspuffar** [comment]
@lyltencent Well depends on your implementation and what you want to accomplice but in my case, I just wanted the x and y coordinates for the boxes and their classification in my file. So I implemented it with simple CSV files.

My code is in a jist
https://gist.github.com/kalaspuffar/24f8f08d5627224a2e002bdddc0fc960

Hope it gives some inspiration to get started at least.

**Comment by lyltencent** [comment]
@kalaspuffar, Hi Daniel, thanks for your information.
